### ISSUE TITLE
migrate unit tests to github actions

### ISSUE THREAD

**Issue by LaurentMontBlanc** [planetmint/planetmint#191]
## Description
Execute the unit-test suite with github actions

## Current State
The travis matrix includes 2x2 unit test jobs:
```yml
matrix:
  fast_finish: true
  include:
  - python: 3.9
    env:
    - PLANETMINT_DATABASE_BACKEND=tarantool_db
    - PLANETMINT_DATABASE_SSL=
  - python: 3.9
    env:
    - PLANETMINT_DATABASE_BACKEND=tarantool_db
    - PLANETMINT_DATABASE_SSL=
    - PLANETMINT_CI_ABCI=enable
  - python: 3.9
    env:
    - PLANETMINT_DATABASE_BACKEND=localmongodb
    - PLANETMINT_DATABASE_SSL=
  - python: 3.9
    env:
    - PLANETMINT_DATABASE_BACKEND=localmongodb
    - PLANETMINT_DATABASE_SSL=
    - PLANETMINT_CI_ABCI=enable 
```

The travis scripts do the following:
 - install docker-compose
 - build planetmint image in 2 configurations (ABCI enabled/disabled)
 - start bdb or planetmint (based on ABCI enabled/disabled)
 - execute pytest (ABCI enabled/disabled)
 
## Proposed State
Create an action in `.github/workflows` that executes the following steps:
 - create a build of planetmint
 - execute pytests with and without ABCI as env var
