### ISSUE TITLE
tests/backend folder issues

### ISSUE THREAD

**Issue by andreitricolici** [planetmint/planetmint#217]
## Problem
In **tests/backend** we have two folders **localmongodb** and **tarantool**.
![DeepinScreenshot_select-area_20220705150950](https://user-images.githubusercontent.com/97448537/177324262-51f11ef4-7a70-40f7-b039-da9c882e2885.png)

For both connection implementation we have following test cases:
  - test_connection.py 
  - test_queries.py
  - test_schema.py

At the moment those are separated, but we need to make them "one entry".

## Comments
Maybe you could use here **singledispatch** module or some features from **pytest library** to create
a better structure.

Also some test function from mongodb can be incompatible with tarantool.
For example, if a test function is checking something specific from mongodb, and this tool or behaviour may not be in tarantool. Take that in mind too.

We must not use python database driver ( not pymongo or tarantool).
Use instead function from **backend/query.py** so it will be flexible for any database.

**Comment by ArpitShukla007** [comment]
@LaurentMontBlanc @andreitricolici I have further researched on issues while running the MongoDB tests and have found that currently we can preconfigure the docker file and other environment variables to one of the two options for database (i.e., MongoDB or Tarantool). 

```
planetmint:
    depends_on:
      #- mongodb
      - tendermint
      - tarantool
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - ./planetmint:/usr/src/app/planetmint
      - ./tests:/usr/src/app/tests
      - ./docs:/usr/src/app/docs
      - ./htmlcov:/usr/src/app/htmlcov
      - ./setup.py:/usr/src/app/setup.py
      - ./setup.cfg:/usr/src/app/setup.cfg
      - ./pytest.ini:/usr/src/app/pytest.ini
      - ./tox.ini:/usr/src/app/tox.ini
    environment:
      PLANETMINT_DATABASE_BACKEND: tarantool_db 
      PLANETMINT_DATABASE_HOST: tarantool
      PLANETMINT_DATABASE_PORT: 3303
      PLANETMINT_SERVER_BIND: 0.0.0.0:9984
      PLANETMINT_WSSERVER_HOST: 0.0.0.0
      PLANETMINT_WSSERVER_ADVERTISED_HOST: planetmint
      PLANETMINT_TENDERMINT_HOST: tendermint
      PLANETMINT_TENDERMINT_PORT: 26657
    ports:
      - "9984:9984"
      - "9985:9985"
      - "26658"
      - "2222:2222"
    healthcheck:
      test: ["CMD", "bash", "-c", "curl http://planetmint:9984 && curl http://tendermint:26657/abci_query"]
      interval: 3s
      timeout: 5s
      retries: 3
```

However, the goal is to test both of the database implementations. This can be achieved in multiple ways. Here is one of the possible solutions:

We can have two separate configurations of planetmint, one with each database. In the make file, for the `make test` command, both of these configurations can be tested separately one after another.

**Comment by LaurentMontBlanc** [comment]
@ArpitShukla007 docker-compose offers the option to use bash like [variable substitution](https://docs.docker.com/compose/compose-file/compose-file-v3/#variable-substitution). I suggest using defining a default value like so: 

```yml
planetmint:
    depends_on:
      - tendermint
      - ${BACKEND:-tarantool}
```

The same applies for environment variables that are used to configure Planetmint to use a specific backend (ports, host, etc.)
