### ISSUE TITLE
use init.lua or yaml for tarantool schema definitions

### ISSUE THREAD

**Issue by LaurentMontBlanc** [planetmint/planetmint#285]
## Description
The current mechanism for initializing the tarantool database uses `subprocess.run` to execute space creation/dropping, space formatting and space indexing. The executed commands are inside objects in `planetmint/backend/tarantool/schema.py`. Schema definitions should be declared in `init.lua`. Tarantool also offers the possibility to use yaml files for these.  For more info see here: [Data schema description](https://www.tarantool.io/en/doc/latest/concepts/data_model/schema_desc/)

## Current State
Commands are stored strings and executed like so:
```python
SPACE_NAMES = (
  "assets"
)

SPACE_COMMANDS = (
  "assets": "assets = box.schema.space.create('assets' , {engine='memtx' , is_sync=false})"
)

# SPACE_INDEX and SPACE_FORMAT are done in similar fashion

def run_command_with_output(command):
    from subprocess import run

    host_port = "%s:%s" % (
        Config().get()["database"]["host"],
        Config().get()["database"]["port"],
    )
    output = run(["tarantoolctl", "connect", host_port], input=command, capture_output=True)
    if output.returncode != 0:
        raise Exception(f"Error while trying to execute cmd {command} on host:port {host_port}: {output.stderr}")
    return output.stdout 
```

## Proposed State
Initialize spaces and indexes with `init.lua`:

```lua
assets = box.schema.space.create('assets' , {engine='memtx' , is_sync=false})
assets:format({{name='data' , type='any'}, {name='tx_id', type='string'}, {name='asset_id', type='string'}})
assets:create_index('txid_search', {type='tree', parts={'tx_id'}})
```

or use a `schema.yml` that is used in `init.lua`:

```yaml
spaces:
  assets:
    engine: memtx
    is_local: false
    temporary: false
    format:
    - {name: data, type: any}
    - {name: tx_id, type: string}
    - {name: asset_id, type: string}
    indexes:
    - name: txid_search
      unique: true
      parts: [{path: tx_id, type: str}]
      type: TREE
```

## Result
This is result offers syntax highlighting, is more in line with tarantool as a whole and less error prone than manipulating strings to change the schema. However, for using yaml the documentation states that these are not to be changed. Migration scenarios must be researched for this.
